"""add_is_online_to_branches

Revision ID: 37f6c5eaf145
Revises: 2e8b82cd62c4
Create Date: 2026-02-24 10:53:33.508259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37f6c5eaf145'
down_revision: Union[str, Sequence[str], None] = '2e8b82cd62c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('is_online', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branches', 'is_online')
    # ### end Alembic commands ###
