"""initial_schema

Revision ID: cae87dca0f53
Revises: 
Create Date: 2026-02-20 09:28:04.002311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cae87dca0f53'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('group_tag', sa.String(length=100), nullable=True),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('volume_music', sa.Integer(), nullable=False),
    sa.Column('volume_announce', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_files',
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Enum('MUSIC', 'ANONS', name='mediatype'), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prayer_times',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('fajr', sa.Time(), nullable=False),
    sa.Column('sunrise', sa.Time(), nullable=False),
    sa.Column('dhuhr', sa.Time(), nullable=False),
    sa.Column('asr', sa.Time(), nullable=False),
    sa.Column('maghrib', sa.Time(), nullable=False),
    sa.Column('isha', sa.Time(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('date', 'city', 'district')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_vendor_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('branch_settings',
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('work_start', sa.Time(), nullable=False),
    sa.Column('work_end', sa.Time(), nullable=False),
    sa.Column('prayer_tracking', sa.Boolean(), nullable=False),
    sa.Column('prayer_margin', sa.Integer(), nullable=False),
    sa.Column('city_code', sa.Integer(), nullable=False),
    sa.Column('loop_mode', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id')
    )
    op.create_table('media_targets',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.Enum('BRANCH', 'GROUP', 'ALL', name='targettype'), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('target_group', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.Enum('BRANCH', 'GROUP', 'ALL', name='targettype'), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('target_group', sa.String(length=100), nullable=True),
    sa.Column('play_at', sa.DateTime(), nullable=True),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedules')
    op.drop_table('media_targets')
    op.drop_table('branch_settings')
    op.drop_table('users')
    op.drop_table('prayer_times')
    op.drop_table('media_files')
    op.drop_table('branches')
    # ### end Alembic commands ###
